# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-13 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=250)),
                ('data', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=250)),
                ('rank', models.CharField(max_length=250)),
                ('company', models.CharField(max_length=250)),
                ('byte', models.CharField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('lil_notice', models.CharField(max_length=500)),
                ('notice', models.CharField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('regn_no', models.CharField(max_length=250)),
                ('CGPA', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=250)),
                ('skill1', models.CharField(max_length=250)),
                ('skill2', models.CharField(max_length=250)),
                ('skill3', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='recruiters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
            ],
        ),
    ]
