# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-17 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='achievements',
        ),
        migrations.AddField(
            model_name='team',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
