# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-18 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180717_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice',
            field=models.TextField(max_length=50000),
        ),
    ]
