# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-18 04:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180717_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='lil_notice',
            field=models.TextField(max_length=500),
        ),
    ]
