# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-18 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180717_2141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notice',
        ),
    ]
