# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-20 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='assign',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
