# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-20 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alumni_assign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profiles',
        ),
    ]
